### ISSUE TITLE
[bug report] class CodecBase free() not working

### ISSUE THREAD

**Issue by EjiHuang** [dubiousconst282/FFmpegWrapper#1]
Hi @dubiousconst282 

When I was developing the player application, I found a memory leak problem. Finally, I located the problem in the `Free()` method of class `CodecBase`. The `_ownsContext` member has always been False causing the method not to be executed.

So, after I set `_ownsContext` to True, the problem was solved.

**Comment by dubiousconst282** [comment]
Hey, thanks for the report! I've published a new release that will hopefully fix this, it should be available on NuGet soon.
