### ISSUE TITLE
SwScaler Convert used dst.Height instead of InputFormat.Height

### ISSUE THREAD

**Issue by RyanYANG52** [dubiousconst282/FFmpegWrapper#5]
first of all, great work, very nice project, appreciate!

I find this bug, when I downscale a raw bitmap to half size

https://github.com/dubiousconst282/FFmpegWrapper/blob/7758e5434be46201c02d189ae1da6df70e833846/FFmpegWrapper/SwScaler.cs#L71

this line should be 
```csharp
ffmpeg.sws_scale(Handle, new[] { pSrc }, new[] { stride }, 0, InputFormat.Height, dst.Handle->data, dst.Handle->linesize).CheckError();
```

**Comment by dubiousconst282** [comment]
Thanks, I've pushed a new release with the fix and an overdue update to FFmpeg 7.0.
